### PR TITLE
Fixes for utility program

### LINKED ISSUE #3: Utility stuck in an infinite loop with certain parameters
Following command gets the utility into an infinite loop (aka 100% CPU utilization with no output).

```
utility --min-value 100000 --max-value 500000 -c 128 -e 10 --verbose
```

### PR DESCRIPTION
**Pull request by dmorton-spirent**
Closes #3

### CODE REVIEW

File: utility/main.cpp [hunk 1]
```diff
@@ -323,10 +323,13 @@ static auto tdigest_trial(const std::vector<Inputs> &values,
...
     double epsilon = -1;
 
-    for (double x = min_value; x <= max_value; x += max_value / 10) {
-      double target = x / max_value;
-      epsilon = std::max(fabs(target - digest.cumulative_distribution(x)),
-                         epsilon);
+    static constexpr unsigned test_count = 10;
+    for (double test_point = 1; test_point <= test_count; test_point++)
+    {
+        auto target = test_point / static_cast<double>(test_count);
```
Comment (DerangedMonkeyNinja) [inline utility/main.cpp]: Nit: Since test_point is a double, I think the cast is unnecessary.
